export const deals = [
  {
    id: "garfield-bungalow",
    title: "Sunlit bungalow with ADU potential",
    neighborhood: "Garfield Historic District",
    city: "Phoenix",
    market: "Phoenix",
    type: "Single family",
    price: 398000,
    estimatedValue: 472000,
    monthlyRent: 3360,
    annualExpenses: 10100,
    beds: 3,
    baths: 2,
    sqft: 1428,
    daysOnMarket: 12,
    marketMomentum: 94,
    renovationReadiness: 82,
    image:
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85",
    tag: "Value gap",
    insight: "Under local comps with room to add a detached studio.",
    detail:
      "Walkable historic core, flexible lot layout, and a strong price-to-rent spread make this the clearest balanced pick.",
  },
  {
    id: "mesa-midcentury",
    title: "Mid-century home near downtown Mesa",
    neighborhood: "Evergreen Historic District",
    city: "Mesa",
    market: "Mesa",
    type: "Single family",
    price: 429000,
    estimatedValue: 493000,
    monthlyRent: 3495,
    annualExpenses: 10500,
    beds: 4,
    baths: 2,
    sqft: 1762,
    daysOnMarket: 18,
    marketMomentum: 88,
    renovationReadiness: 90,
    image:
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=85",
    tag: "Rental ready",
    insight: "Four-bedroom demand and minimal repair exposure.",
    detail:
      "A move-in-ready layout in a transit-friendly pocket produces a durable cash-flow profile without a major renovation timeline.",
  },
  {
    id: "tucson-fourplex",
    title: "Fourplex with separate shaded courtyards",
    neighborhood: "Blenman-Elm",
    city: "Tucson",
    market: "Tucson",
    type: "Multi-family",
    price: 620000,
    estimatedValue: 688000,
    monthlyRent: 5680,
    annualExpenses: 16800,
    beds: 6,
    baths: 4,
    sqft: 3210,
    daysOnMarket: 9,
    marketMomentum: 86,
    renovationReadiness: 88,
    image:
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=85",
    tag: "Cash-flow",
    insight: "Four income streams lower vacancy exposure.",
    detail:
      "Near the university and hospital corridor, this compact fourplex pairs income diversity with unusually low days on market.",
  },
  {
    id: "arcadia-courtyard",
    title: "Courtyard home beneath mature citrus",
    neighborhood: "Arcadia Lite",
    city: "Phoenix",
    market: "Phoenix",
    type: "Single family",
    price: 645000,
    estimatedValue: 707000,
    monthlyRent: 4780,
    annualExpenses: 15900,
    beds: 3,
    baths: 2,
    sqft: 1840,
    daysOnMarket: 25,
    marketMomentum: 96,
    renovationReadiness: 74,
    image:
      "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=1200&q=85",
    tag: "High demand",
    insight: "Premium neighborhood at a relative discount.",
    detail:
      "The strongest appreciation signal in the set, with a layout that supports premium furnished-rental positioning.",
  },
  {
    id: "tempe-townhome",
    title: "Quiet townhome near Tempe Town Lake",
    neighborhood: "Marina Heights",
    city: "Tempe",
    market: "Tempe",
    type: "Townhome",
    price: 454000,
    estimatedValue: 492000,
    monthlyRent: 3350,
    annualExpenses: 10900,
    beds: 3,
    baths: 2.5,
    sqft: 1580,
    daysOnMarket: 31,
    marketMomentum: 91,
    renovationReadiness: 84,
    image:
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=85",
    tag: "Low friction",
    insight: "Low-maintenance ownership near job density.",
    detail:
      "A newer townhome with rental appeal to university and tech workers, balanced by manageable carrying costs.",
  },
  {
    id: "old-town-condo",
    title: "Lock-and-leave condo with mountain light",
    neighborhood: "Old Town",
    city: "Scottsdale",
    market: "Scottsdale",
    type: "Condo",
    price: 514000,
    estimatedValue: 558000,
    monthlyRent: 3880,
    annualExpenses: 15300,
    beds: 2,
    baths: 2,
    sqft: 1298,
    daysOnMarket: 21,
    marketMomentum: 92,
    renovationReadiness: 86,
    image:
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=85",
    tag: "Short-term appeal",
    insight: "Hospitality demand supports rate resilience.",
    detail:
      "A compact lifestyle asset close to dining and spring training, with a location premium that anchors downside protection.",
  },
  {
    id: "north-central-ranch",
    title: "Classic ranch with a deep backyard",
    neighborhood: "North Central",
    city: "Phoenix",
    market: "Phoenix",
    type: "Single family",
    price: 569000,
    estimatedValue: 604000,
    monthlyRent: 4120,
    annualExpenses: 15100,
    beds: 3,
    baths: 2,
    sqft: 1946,
    daysOnMarket: 43,
    marketMomentum: 89,
    renovationReadiness: 67,
    image:
      "https://images.unsplash.com/photo-1600585152915-d208bec867a1?auto=format&fit=crop&w=1200&q=85",
    tag: "Lot upside",
    insight: "A generous lot leaves expansion options open.",
    detail:
      "The largest outdoor footprint in the collection, with a stable neighborhood signal and room for phased improvements.",
  },
  {
    id: "chandler-casita",
    title: "Desert-modern home with guest casita",
    neighborhood: "Ocotillo",
    city: "Chandler",
    market: "Chandler",
    type: "Single family",
    price: 685000,
    estimatedValue: 718000,
    monthlyRent: 4860,
    annualExpenses: 18400,
    beds: 4,
    baths: 3,
    sqft: 2360,
    daysOnMarket: 16,
    marketMomentum: 90,
    renovationReadiness: 80,
    image:
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1200&q=85",
    tag: "Guest income",
    insight: "Flexible guest space broadens tenant demand.",
    detail:
      "A polished primary residence with a separate suite, giving long-term tenants or visiting professionals a differentiated option.",
  },
  {
    id: "peoria-pool-home",
    title: "Pool home close to trail access",
    neighborhood: "Vistancia",
    city: "Peoria",
    market: "Peoria",
    type: "Single family",
    price: 535000,
    estimatedValue: 552000,
    monthlyRent: 3820,
    annualExpenses: 16200,
    beds: 4,
    baths: 2.5,
    sqft: 2184,
    daysOnMarket: 37,
    marketMomentum: 82,
    renovationReadiness: 76,
    image:
      "https://images.unsplash.com/photo-1600047509358-9dc75507daeb?auto=format&fit=crop&w=1200&q=85",
    tag: "Family demand",
    insight: "Space and amenities favor long-term leases.",
    detail:
      "A practical suburban rental with four bedrooms, a private pool, and a dependable family-renter profile.",
  },
];

export const marketOptions = [
  "All Arizona",
  "Phoenix",
  "Scottsdale",
  "Mesa",
  "Tempe",
  "Tucson",
  "Chandler",
  "Peoria",
];
