import type { City, Condition, Deal, DealKind, Pricing } from "../types";
import type { Category } from "../types";

type CatalogSeed = {
  id: string;
  title: string;
  description: string;
  category: Category;
  city: City;
  askingPrice: number;
  marketPrice: number;
  estimatedResale?: number;
  monthlyRent?: number;
  condition: Condition;
  pricing?: Pricing;
  kind?: DealKind;
  postedHoursAgo: number;
  tags: string[];
  arizonaFit?: number;
};

const SEEDS: CatalogSeed[] = [
  {
    id: "mesa-window-ac",
    title: "LG 12,000 BTU window AC, like new",
    description: "Used one summer in Mesa. Remote and side panels included. Seller upgrading to a mini-split.",
    category: "cooling",
    city: "Mesa",
    askingPrice: 90,
    marketPrice: 280,
    estimatedResale: 210,
    condition: "like-new",
    postedHoursAgo: 4,
    tags: ["must-sell", "pickup"],
  },
  {
    id: "phoenix-swamp-cooler",
    title: "Portable swamp cooler, works great",
    description: "Evaporative cooler for a garage or patio. Reservoir clean, wheels intact.",
    category: "cooling",
    city: "Phoenix",
    askingPrice: 60,
    marketPrice: 220,
    estimatedResale: 170,
    condition: "good",
    postedHoursAgo: 7,
    tags: ["garage", "evaporative"],
  },
  {
    id: "ahwatukee-mini-split",
    title: "Unused 12k mini-split kit, still boxed",
    description: "DIY 115V mini-split. Bought for a casita, never installed. Lineset in box.",
    category: "cooling",
    city: "Phoenix",
    askingPrice: 520,
    marketPrice: 1200,
    estimatedResale: 860,
    condition: "new",
    postedHoursAgo: 11,
    tags: ["new-in-box"],
  },
  {
    id: "tucson-patio-set",
    title: "5-piece patio dining set with umbrella",
    description: "Steel frames, fresh cushions. Moving out of a midtown rental this weekend.",
    category: "outdoor",
    city: "Tucson",
    askingPrice: 125,
    marketPrice: 450,
    estimatedResale: 300,
    condition: "good",
    postedHoursAgo: 6,
    tags: ["moving"],
  },
  {
    id: "gilbert-pool-pump",
    title: "Pentair pool pump, pulled working",
    description: "Replaced during a remodel. Primed and ran last week. 1.5 HP.",
    category: "outdoor",
    city: "Gilbert",
    askingPrice: 75,
    marketPrice: 280,
    estimatedResale: 200,
    condition: "good",
    postedHoursAgo: 9,
    tags: ["pool"],
  },
  {
    id: "tempe-ebike",
    title: "Lectric XP e-bike, 40 miles on it",
    description: "Campus commuter. Battery healthy, extra charger, rear rack.",
    category: "vehicles",
    city: "Tempe",
    askingPrice: 380,
    marketPrice: 900,
    estimatedResale: 680,
    condition: "like-new",
    postedHoursAgo: 14,
    tags: ["campus"],
  },
  {
    id: "phoenix-civic",
    title: "2016 Honda Civic LX, 118k, clean title",
    description: "Highway miles, recent tires, AC blows cold. One-owner Valley car.",
    category: "vehicles",
    city: "Phoenix",
    askingPrice: 9800,
    marketPrice: 14500,
    estimatedResale: 13200,
    condition: "good",
    postedHoursAgo: 18,
    tags: ["clean-title"],
  },
  {
    id: "glendale-f150",
    title: "2012 Ford F-150 XLT 4x4, 142k",
    description: "Work truck with a fresh battery and cold AC. Small bed dents, no rust.",
    category: "vehicles",
    city: "Glendale",
    askingPrice: 8900,
    marketPrice: 16500,
    estimatedResale: 14800,
    condition: "fair",
    postedHoursAgo: 22,
    tags: ["truck"],
  },
  {
    id: "flagstaff-mtb",
    title: "Trek mountain bike, tuned this spring",
    description: "Hardtail, new pads, ready for Schultz Pass. Selling before a move.",
    category: "vehicles",
    city: "Flagstaff",
    askingPrice: 85,
    marketPrice: 220,
    estimatedResale: 160,
    condition: "good",
    postedHoursAgo: 8,
    tags: ["outdoor"],
  },
  {
    id: "chandler-washer",
    title: "Matching washer and dryer pair",
    description: "Both spin and heat. Pedestals not included. Neighborhood pickup only.",
    category: "appliances",
    city: "Chandler",
    askingPrice: 220,
    marketPrice: 700,
    estimatedResale: 480,
    condition: "good",
    postedHoursAgo: 5,
    tags: ["laundry"],
  },
  {
    id: "surprise-water-softener",
    title: "Whirlpool water softener, detached",
    description: "Hard-water Valley home upgraded to a larger unit. Resin still good.",
    category: "appliances",
    city: "Surprise",
    askingPrice: 200,
    marketPrice: 700,
    estimatedResale: 500,
    condition: "good",
    postedHoursAgo: 16,
    tags: ["hard-water"],
  },
  {
    id: "tempe-fridge",
    title: "Mini fridge, dorm move-out",
    description: "Works, freezer ices up slowly. Free if you also take the lamp — asking $40.",
    category: "appliances",
    city: "Tempe",
    askingPrice: 40,
    marketPrice: 180,
    estimatedResale: 110,
    condition: "fair",
    postedHoursAgo: 3,
    tags: ["move-out"],
  },
  {
    id: "scottsdale-sofa",
    title: "West Elm sofa, pet-free home",
    description: "Oatmeal fabric, no stains. Replacing with a sectional.",
    category: "furniture",
    city: "Scottsdale",
    askingPrice: 400,
    marketPrice: 1600,
    estimatedResale: 850,
    condition: "like-new",
    postedHoursAgo: 20,
    tags: ["designer"],
  },
  {
    id: "mesa-dining",
    title: "Solid wood dining table, seats 6",
    description: "Heavy oak. Chairs sold separately. Need it gone before Saturday.",
    category: "furniture",
    city: "Mesa",
    askingPrice: 50,
    marketPrice: 250,
    estimatedResale: 160,
    condition: "good",
    postedHoursAgo: 2,
    tags: ["must-sell"],
  },
  {
    id: "phoenix-mattress",
    title: "Queen hybrid mattress, 8 months old",
    description: "Slept on with a protector. Smoke-free. Encased in a bag for transport.",
    category: "furniture",
    city: "Phoenix",
    askingPrice: 120,
    marketPrice: 500,
    estimatedResale: 260,
    condition: "good",
    postedHoursAgo: 10,
    tags: ["queen"],
  },
  {
    id: "gilbert-crib",
    title: "Convertible crib, all hardware",
    description: "Recalled parts already replaced. Mattress not included.",
    category: "furniture",
    city: "Gilbert",
    askingPrice: 40,
    marketPrice: 180,
    estimatedResale: 90,
    condition: "good",
    postedHoursAgo: 13,
    tags: ["baby"],
  },
  {
    id: "phoenix-suns-tix",
    title: "Suns lower-level pair, this week",
    description: "Two seats together, face value $120 each. Can't make the game.",
    category: "tickets",
    city: "Phoenix",
    askingPrice: 90,
    marketPrice: 220,
    estimatedResale: 170,
    condition: "new",
    postedHoursAgo: 6,
    tags: ["suns"],
  },
  {
    id: "yuma-generator",
    title: "Westinghouse 4500W generator",
    description: "Used for two outages. Extra oil and cover included.",
    category: "tools",
    city: "Yuma",
    askingPrice: 150,
    marketPrice: 400,
    estimatedResale: 300,
    condition: "good",
    postedHoursAgo: 15,
    tags: ["power"],
  },
  {
    id: "tucson-tools",
    title: "Craftsman 200-piece mechanic set",
    description: "Mostly complete, missing a 10mm (of course). Case hinges fine.",
    category: "tools",
    city: "Tucson",
    askingPrice: 40,
    marketPrice: 160,
    estimatedResale: 110,
    condition: "fair",
    postedHoursAgo: 9,
    tags: ["tools"],
  },
  {
    id: "oro-valley-mower",
    title: "Craftsman riding mower, starts first pull",
    description: "Deck solid, new belt. Too much machine for a smaller lot.",
    category: "tools",
    city: "Tucson",
    askingPrice: 300,
    marketPrice: 800,
    estimatedResale: 560,
    condition: "good",
    postedHoursAgo: 26,
    tags: ["yard"],
  },
  {
    id: "phoenix-solar-fan",
    title: "Solar attic fan, used one season",
    description: "Pulled during a reroof. Thermostat works. 20W panel.",
    category: "solar",
    city: "Phoenix",
    askingPrice: 35,
    marketPrice: 120,
    estimatedResale: 85,
    condition: "good",
    postedHoursAgo: 5,
    tags: ["attic"],
  },
  {
    id: "chandler-tv",
    title: "55-inch 4K TV, no remote",
    description: "Picture is fine, one dead pixel. Use any universal remote.",
    category: "electronics",
    city: "Chandler",
    askingPrice: 140,
    marketPrice: 380,
    estimatedResale: 240,
    condition: "fair",
    postedHoursAgo: 12,
    tags: ["tv"],
  },
  {
    id: "tempe-macbook",
    title: "MacBook Air 2019, 8/256, battery 84%",
    description: "Student machine, dings on the bottom. Charger included.",
    category: "electronics",
    city: "Tempe",
    askingPrice: 280,
    marketPrice: 520,
    estimatedResale: 420,
    condition: "good",
    postedHoursAgo: 17,
    tags: ["laptop"],
  },
  {
    id: "peoria-iphone",
    title: "iPhone 13, 128GB, unlocked",
    description: "Light scratches, battery 87%. Face ID works. No charger.",
    category: "electronics",
    city: "Peoria",
    askingPrice: 260,
    marketPrice: 320,
    estimatedResale: 280,
    condition: "good",
    postedHoursAgo: 8,
    tags: ["phone"],
  },
  {
    id: "mesa-kitchenaid",
    title: "KitchenAid stand mixer, artisan red",
    description: "Bowl, whisk, dough hook. Used for bread, not a display piece.",
    category: "appliances",
    city: "Mesa",
    askingPrice: 80,
    marketPrice: 350,
    estimatedResale: 240,
    condition: "good",
    postedHoursAgo: 4,
    tags: ["kitchen"],
  },
  {
    id: "phoenix-house-maryvale",
    title: "Maryvale 3/2, 1,412 sq ft, motivated seller",
    description: "Updated AC in 2023, block construction. Needs paint and flooring. Tenant-ready in 30 days.",
    category: "housing",
    city: "Phoenix",
    askingPrice: 265000,
    marketPrice: 318000,
    monthlyRent: 1850,
    condition: "fair",
    pricing: "sale",
    kind: "housing",
    postedHoursAgo: 30,
    tags: ["investment", "value-add"],
    arizonaFit: 92,
  },
  {
    id: "tucson-duplex",
    title: "Midtown Tucson duplex, both sides occupied",
    description: "Separate meters, newer roofs. Rents $1,150 and $1,050. No HOA.",
    category: "housing",
    city: "Tucson",
    askingPrice: 219000,
    marketPrice: 268000,
    monthlyRent: 2200,
    condition: "good",
    pricing: "sale",
    kind: "housing",
    postedHoursAgo: 40,
    tags: ["duplex", "cash-flow"],
    arizonaFit: 94,
  },
  {
    id: "mesa-townhome",
    title: "Mesa townhome 2/2 listed at neighborhood ask",
    description: "Clean, HOA $240. Priced with the last three comps, not a discount.",
    category: "housing",
    city: "Mesa",
    askingPrice: 310000,
    marketPrice: 305000,
    monthlyRent: 1750,
    condition: "like-new",
    pricing: "sale",
    kind: "housing",
    postedHoursAgo: 12,
    tags: ["hoa"],
    arizonaFit: 88,
  },
  {
    id: "tempe-studio-rent",
    title: "Tempe studio, 10-minute bike to ASU",
    description: "Utilities included except electric. Available next month. Below campus comps.",
    category: "housing",
    city: "Tempe",
    askingPrice: 1050,
    marketPrice: 1450,
    condition: "good",
    pricing: "monthly",
    kind: "housing",
    postedHoursAgo: 9,
    tags: ["rent", "campus"],
    arizonaFit: 90,
  },
  {
    id: "scottsdale-lamp",
    title: "Vintage Mid-century lamp, 'rare'",
    description: "Seller wants collector money. Shade stained, switch is finicky. Pretty, not a deal.",
    category: "furniture",
    city: "Scottsdale",
    askingPrice: 220,
    marketPrice: 80,
    estimatedResale: 55,
    condition: "fair",
    postedHoursAgo: 3,
    tags: ["overpriced"],
    arizonaFit: 40,
  },
  {
    id: "phoenix-socks",
    title: "New athletic socks, 6-pack",
    description: "Retail leftover. Fine product, almost no discount.",
    category: "other",
    city: "Phoenix",
    askingPrice: 12,
    marketPrice: 14,
    estimatedResale: 6,
    condition: "new",
    postedHoursAgo: 1,
    tags: ["thin-margin"],
    arizonaFit: 22,
  },
];

export function loadCatalog(now = Date.now()): Deal[] {
  return SEEDS.map((seed) => {
    const postedAt = new Date(now - seed.postedHoursAgo * 3_600_000).toISOString();
    return {
      id: `catalog:${seed.id}`,
      title: seed.title,
      description: seed.description,
      category: seed.category,
      city: seed.city,
      askingPrice: seed.askingPrice,
      marketPrice: seed.marketPrice,
      estimatedResale: seed.estimatedResale ?? Math.round(seed.marketPrice * 0.78),
      monthlyRent: seed.monthlyRent ?? null,
      condition: seed.condition,
      pricing: seed.pricing ?? "sale",
      kind: seed.kind ?? "local",
      source: "catalog",
      sourceLabel: "Arizona local sample",
      url: `#${seed.id}`,
      postedAt,
      tags: seed.tags,
      arizonaFit: seed.arizonaFit ?? 86,
    };
  });
}

export const CATALOG_COUNT = SEEDS.length;
